---
title: Cómo escribir manuscritos reproducibles
subtitle: With a subtitle
author: Francisco Rodríguez-Sánchez
date: \today
institute: Centre for Modern Beamer Themes
output: binb::metropolis
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```


## Reproducibilidad

Turing table

## Reproducibilidad: buena para ti, buena para todos

List of indiv & communal benefits


## La reproducibilidad es un gradiente

Fig 1. ecosistemas (modif. Peng Science 2011)


## Simplest reproducibility

Share data (github, piggyback, repos) and code. Archived on public repository (not website, not github, eg Zenodo, figshare, dryad, etc)

Bonus: include sessioninfo

Git Version control

We're still far from that

## Main barriers are not technical

Antica Plos Biol. Most people using R, but not sharing

Publish your code: is good enough.
(and if it not, maybe you need to learn more, or collaborate w/ people who can help?)
Community: be constructive, not shaming. Ugly code better than no code


# Literate programming: Rmarkdown

Tedious to repeat, etc (examples from Rmd workshops and paper)

## What's Rmd

## Rmarkdown inline vs copy/paste



## Rmd: regenerate Word/PDF/html etc dynamically with one click


## Automatic model tables

## Figures

## Equations


## Citations

citr, rbbt, rcrossref, CSL


## Rmd templates

rticles, papaja, etc


## Not only R! Computing in many languages

https://bookdown.org/yihui/rmarkdown/language-engines.html


# Research compendium

## Minimal

Boettiger

## pkg

## ADvantages

- Data, text, code



Continuous integration. Travis, GH actions



Critique (McBain)

Data external repo, then imported

rrtools

sessioninfo, description


# Dependencies

- checkpoint, automagic, renv

# Docker

- repo2docker

- containerit



# Binder/Holepunch

- elife ERA



# Workflow

## makefile.R

## Drake/targets









## Resources

https://rmd4sci.njtierney.com/

rmd bookdowns


https://annakrystalli.me/rrtools-repro-research/

https://annakrystalli.me/talks/user2020.html#1

https://annakrystalli.me/talks/r-in-repro-research-dc-leedsrss.html#1

https://codecheck.org.uk/

https://nevrome.github.io/rrtools.tutorial.mpi2020/

Karthik's talk








